extend-include = ["*.ipynb"]
show-fixes = true
src = ["hack", "src"]

[lint]
extend-select = ["I"]
preview = true

[lint.isort]
case-sensitive = true
combine-as-imports = false
default-section = "third-party"
from-first = false
known-first-party = ["clsx"]
lines-after-imports = 2
lines-between-types = 1
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
